identifier: skean
name: Skean
type: keyboard
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - gpio
  - counter
  - spi
  - usb_device
  - lsm303dlhc
  - nvs
  - can
  - kscan
  - ble